### ISSUE TITLE
Remove  "inner-content-padding-fix" workaround from app.less

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#1587]
V minulosti som zaviedol:

https://github.com/keboola/kbc-ui/blob/9139d6ab774f7ffbaed7bc759255a460ffb75a44/src/styles/app.less#L333-L339

Bolo to preto, ze som chcel zamedzit pouzitiu `row kbc-header`.

Prave toto je ostylovane takto:

```css
.kbc-main-content>.row, .kbc-main>.container-fluid>form>.row, .kbc-main-content-with-nav>.row, .kbc-main-content-with-sidebar>.row, .kbc-row {
    margin: 0;
    padding: 22px;
    border-bottom: 1px solid #e8e8ef;
}
```

a

```css
.kbc-main .kbc-header {
    padding: 22px 22px 15px !important;
}
```

Pricom to prve je fail, druhe je relativne ok.

---

V tomto issue by som chcel vyhodit ten moj workaroud a nahradit to za `kbc-header kbc-header-with-bottom-border` -> t.j. nebude tam pouziva layout class `row`.

Toto som pridal nedavno:

https://github.com/keboola/indigo-ui/blob/dd8851213f1a1b07d625c4266bf834c37099ede9/src/indigo/less/main-content.less#L32-L34

`kbc-inner-content-padding-fix` sa pouziva na 58 miestach, nic zlozite, 2x search/replace.

@janmichek mas k tomu nieco?
