### ISSUE TITLE
Button toolbar - usages outside modal broken

### ISSUE THREAD

**Issue by ujovlado** [keboola/kbc-ui#2405]
Related: #2347

@janmichek  Tym ze sa tam pridal ten toolbar, tak plati:

```css
.btn-toolbar .btn, .btn-toolbar .btn-group, .btn-toolbar .input-group {
    float: left;
}
```

co je v modaloch ok, lebo tam sa to fixuje:
```css
.modal-dialog .modal-footer .btn-toolbar > .btn {
    float: none;
}
```

ale ostatne pouzitia su rozbite.

Trosku som to upravil v #2404, ale aj tak je to zle, pretoze je loader vpravo, ked ma byt vlavo.

Vsimol som si to najma v:

- vytvaranie tokenu
- editacia taskov v orchestracii

Viac som to neskumal.
